const ivyliaResponses = [
  "One moment, I'm counting fishies in my head! ヽ(=^･ω･^=)丿",
  "Pawsing for a thought... be right back! (＾• ω •＾)",
  "Fish and sweets on my mind... Please hold on! (ฅ^•ﻌ•^ฅ)",
  "I'm on a yarn ball roll... just a sec! (=^-ω-^=)",
  "Just a whisker of a moment, thinking time! (ΦωΦ)",
  "Scratching up some ideas... wait up! (=`ω´=)",
  "Hang on, I'm purr-ocessing... (=^･ω･^=)",
  "Let me meow-ld over that... stay tuned! (･∀･)",
  "I'm chasing a thought like a laser pointer... hold on! (=^ェ^=)",
  "Wait for a mew-ment, I'm getting there! ヽ(=^･ω･^=)丿",
  "Purr-lease wait, calculating my next pounce! (＾• ω •＾)",
  "Fishing for answers, be right back! (ฅ^•ﻌ•^ฅ)",
  "Give me a second, sorting through my kitty dreams... (ΦωΦ)",
  "I'm knitting my thoughts together... one moment! (=^-ω-^=)",
  "Let's paws for a brief catnap... thinking in progress! (=`ω´=)",
  "Gimme a whisker... I'm onto something! (＾• ω •＾)",
  "Compiling my cattitude... please hold! (ฅ^•ﻌ•^ฅ)",
  "I'm in the middle of a purrfect thought... one sec! (=^･ω･^=)",
  "Just a tail flick away from an answer... wait please! (･∀･)",
  "Taking a short cat walk, be back with an idea! (=^ェ^=)",
  "I'm curling up with my thoughts... hold on a mewment! (＾• ω •＾)",
  "Give me a treat's worth of time... thinking! ヽ(=^･ω･^=)丿",
  "Whiskers twitching... brain is booting... wait up! (ฅ^•ﻌ•^ฅ)",
  "Be patient, I'm sharpening my claws and thoughts! (=`ω´=)",
  "Fluffing my fur and gathering thoughts... one moment! (=^-ω-^=)",
  "I'm on a purr-suit of knowledge... hang tight! (＾• ω •＾)",
  "Tail is wagging... brain is chugging... please wait! (ΦωΦ)",
  "Gazing out the window to catch a thought... brb! (ฅ^•ﻌ•^ฅ)",
  "I'm pawndering deeply... give me a sec! (＾• ω •＾)",
  "Curling up with a good thought... hold on! (=`ω´=)",
  "I'm busy being adorably contemplative... wait a whisker! (=^-ω-^=)",
  "Purrhaps I need a moment... thinking time! (･∀･)",
  "A cat's gotta do what a cat's gotta mew... thinking! (＾• ω •＾)",
  "Let me pounce on that thought... one moment, please! (ฅ^•ﻌ•^ฅ)",
  "Shuffling my paws... almost there... wait please! (ΦωΦ)",
  "Gimme a purrfect minute... just contemplating! (＾• ω •＾)",
  "Fetching some ideas from my toy box... be right back! (=^-ω-^=)",
  "Whiskers in a twist... I'm getting to it... please hold! (=`ω´=)",
  "I'm paw-lyzing the situation... hang on a mewment! (･∀･)",
  "Almost caught the red dot of inspiration... wait up! (＾• ω •＾)",
  "Navigating a cat tree of thoughts... one sec! ヽ(=^･ω･^=)丿",
  "I might look like I'm napping, but I'm really thinking... hold please! (ΦωΦ)",
  "Just a little cat loaf thinking time needed... brb!",
];

export const getRandomIvyliaResponse = () => {
  const randomIndex = Math.floor(Math.random() * ivyliaResponses.length);
  return ivyliaResponses[randomIndex];
}